### ISSUE TITLE
helloworld-native-application - Debugger Issue

### ISSUE THREAD

**Issue by ashwindv1** [iotbzh/helloworld-native-application#4]
Hello,

I am following [this](https://iot.bzh/download/public/XDS/docs/XDS_UsersGuide_v6.0.0.pdf) documentation. My end goal is to setup IDE with XDS server to ease the development.

I am able to build the App, but the problem is with debugger,
When I tried to run the command, 

xds-cli exec -- cmake -DRSYNC_TARGET=root@myTarget ..

CMake Error at conf.d/cmake/config.cmake:196 (include):
  include could not find requested file:

    CMakeAfbTemplates
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Configuring incomplete, errors occurred! 

I tried PKG_CONFIG_PATH, but no luck!

Existing answers online or either not working or the links they suggest has been moved permanently.

Kindly guide me resolve the issue. 

Best Regards,
Ashwin

**Comment by kooltux** [comment]
Hi Ashwin, thanks for testing this.
However, this repository is a bit old and should be deprecated IMO.

If you're interested by our latest developments on application framework and binder/bindings, I strongly encourage you to follow the guides located on https://docs.redpesk.bzh/docs/en/master/getting_started/host-configuration/docs/0-build-microservice-overview.html
